server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: notification-serivce
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.benisme.notificationservice.event.OrderPlacedEvent

management:
  tracing:
    sampling:
      probability: 1.0