spring:
  kafka:
    bootstrap-servers: broker:29092

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      default-zone: http://discovery-server:8761/eureka