spring:
  datasource:
    url: jdbc:postgresql://order-postgres:5431/order-service
    driver-class-name: org.postgresql.Driver
    username: ben
    password: ben1234
  kafka:
    bootstrap-servers: broker:29092

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      default-zone: http://discovery-server:8761/eureka