server:
  port: 0

spring:
  profiles:
    active: dev
  application:
    name: product-service

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka


---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service-dev
      auto-index-creation: true

---

spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service-test
      auto-index-creation: true
