server:
  port: 0

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service-dev
      auto-index-creation: true

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

