server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://inventory-postgres:5432/inventory-service
    username: ben
    password: ben1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@discovery-server:8761/eureka